all:
	g++ exercise3.1-a.cpp -o exercise3.1-a
	g++ exercise3.1-b.cpp -o exercise3.1-b
	g++ exercise3.1-c.cpp -o exercise3.1-c
	g++ exercise3.1-d.cpp -o exercise3.1-d
	g++ exercise3.1-e.cpp -o exercise3.1-e
	g++ exercise3.1-f.cpp -o exercise3.1-f
	g++ exercise3.1-g.cpp -o exercise3.1-g
	g++ exercise3.1-h.cpp -o exercise3.1-h

clean:
	rm -rf exercise3.1-a
	rm -rf exercise3.1-b
	rm -rf exercise3.1-c
	rm -rf exercise3.1-d
	rm -rf exercise3.1-e
	rm -rf exercise3.1-f
	rm -rf exercise3.1-g
	rm -rf exercise3.1-h
