all:
	g++ -c TreeNode.cpp -o TreeNode.o
	g++ -c BinStrTree.cpp -o BinStrTree.o
	g++ -c exercise13.28.cpp -o exercise13.28.o
	g++ TreeNode.o BinStrTree.o exercise13.28.o -o main

clean:
	rm -rf TreeNode.o BinStrTree.o exercise13.28.o main

