all:
	g++ exercise11.13_1.cpp -o exercise11.13_1
	g++ exercise11.13_2.cpp -o exercise11.13_2
	g++ exercise11.13_3.cpp -o exercise11.13_3

clean:
	rm -rf exercise11.13_1 exercise11.13_2 exercise11.13_3

