all:
	g++ 01_constructor_and_destructor.cpp -o 01_constructor_and_destructor
	g++ 02_copy_constructor.cpp -o 02_copy_constructor
	g++ 03_copy_assignment.cpp -o 03_copy_assignment
	g++ 04_pass_as_reference.cpp -o 04_pass_as_reference
	g++ 05_pass_as_nonreference.cpp -o 05_pass_as_nonreference
	g++ 06_dynamically_allocate.cpp -o 06_dynamically_allocate
	g++ 07_put_in_a_vector.cpp -o 07_put_in_a_vector

clean:
	rm -rf 01_constructor_and_destructor
	rm -rf 02_copy_constructor
	rm -rf 03_copy_assignment
	rm -rf 04_pass_as_reference
	rm -rf 05_pass_as_nonreference
	rm -rf 06_dynamically_allocate
	rm -rf 07_put_in_a_vector

