all:
	g++ exercise13.14.cpp -o exercise13.14
	g++ exercise13.15.cpp -o exercise13.15
	g++ exercise13.16.cpp -o exercise13.16

clean:
	rm -rf exercise13.14
	rm -rf exercise13.15
	rm -rf exercise13.16

