all:
	g++ exercise3.43-a.cpp -std=c++11 -Wall -Og -o exercise3.43-a
	g++ exercise3.43-b.cpp -std=c++11 -Wall -Og -o exercise3.43-b
	g++ exercise3.43-c.cpp -std=c++11 -Wall -Og -o exercise3.43-c

clean:
	rm -rf exercise3.43-a exercise3.43-b exercise3.43-c
