all:
	g++ exercise2.41-a.cpp -o exercise2.41-a
	g++ exercise2.41-b.cpp -o exercise2.41-b
	g++ exercise2.41-c.cpp -o exercise2.41-c
	g++ exercise2.41-d.cpp -o exercise2.41-d
	g++ exercise2.41-e.cpp -o exercise2.41-e

clean:
	rm -rf exercise2.41-a
	rm -rf exercise2.41-b
	rm -rf exercise2.41-c
	rm -rf exercise2.41-d
	rm -rf exercise2.41-e
