all:
	g++ -c StrBlob.cpp -o StrBlob.o
	g++ -c StrBlobPtr.cpp -o StrBlobPtr.o
	g++ -c exercise13.26.cpp -o exercise13.26.o
	g++ StrBlob.o StrBlobPtr.o exercise13.26.o -o main

clean:
	rm -rf *.o main

