all:
	g++ exercise2.42-a.cpp -o exercise2.42-a
	g++ exercise2.42-b.cpp -o exercise2.42-b
	g++ exercise2.42-c.cpp -o exercise2.42-c
	g++ exercise2.42-d.cpp -o exercise2.42-d
	g++ exercise2.42-e.cpp -o exercise2.42-e

clean:
	rm -rf exercise2.42-a
	rm -rf exercise2.42-b
	rm -rf exercise2.42-c
	rm -rf exercise2.42-d
	rm -rf exercise2.42-e
