all:
	g++ -c StrBlob.cpp -o StrBlob.o
	g++ -c StrBlobPtr.cpp -o StrBlobPtr.o
	g++ -c exercise12.20.cpp -o exercise12.20.o
	g++ StrBlob.o StrBlobPtr.o exercise12.20.o -o main

clean:
	rm -rf *.o main

